/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pi' at '01/11/15 18:27' with Gradle 2.8
 *
 * @author pi, @date 01/11/15 18:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
